// tina/config.ts
import { defineConfig } from 'tinacms';

export default defineConfig({
  branch: process.env.TINA_BRANCH || process.env.HEAD || 'main',
  clientId: process.env.TINA_CLIENT_ID || '',
  token: process.env.TINA_TOKEN || '',
  build: {
    outputFolder: 'admin',
    publicFolder: 'public',
  },
  media: {
    tina: {
      mediaRoot: 'images',
      publicFolder: 'public',
    },
  },
  schema: {
    collections: [
      {
        name: 'homepage',
        label: 'Homepage',
        path: 'src/content/pages',
        format: 'json',
        match: { include: 'homepage.json' },
        ui: {
          allowedActions: { create: false, delete: false },
          router: () => '/',
        },
        fields: [
          { type: 'string', name: 'seo_title', label: 'Page Title (Browser Tab)' },
          { type: 'string', name: 'seo_description', label: 'Page Description (Google)', ui: { component: 'textarea' } },
          {
            type: 'object',
            name: 'hero',
            label: 'Hero Section',
            fields: [
              { type: 'image', name: 'image', label: 'Background Image' },
              { type: 'string', name: 'image_alt', label: 'Image Alt Text' },
              { type: 'string', name: 'caption', label: 'Location Label (e.g. "Bad Wurzach · Allgäu")' },
              { type: 'string', name: 'headline_line1', label: 'Headline Line 1' },
              { type: 'string', name: 'headline_line2', label: 'Headline Line 2 (italic, highlighted)' },
              { type: 'string', name: 'body', label: 'Intro Text', ui: { component: 'textarea' } },
              { type: 'string', name: 'cta_primary_label', label: 'Primary Button Text' },
              { type: 'string', name: 'cta_primary_href', label: 'Primary Button Link' },
              { type: 'string', name: 'cta_secondary_label', label: 'Secondary Button Text' },
              { type: 'string', name: 'cta_secondary_href', label: 'Secondary Button Link' },
            ],
          },
          {
            type: 'object',
            name: 'pillars',
            label: 'Three Pillars',
            fields: [
              {
                type: 'object',
                name: 'moorheilbad',
                label: '01 – Moorheilbad',
                fields: [
                  { type: 'string', name: 'number', label: 'Number (e.g. "01")' },
                  { type: 'string', name: 'heading', label: 'Heading' },
                  { type: 'string', name: 'body', label: 'Description', ui: { component: 'textarea' } },
                ],
              },
              {
                type: 'object',
                name: 'therme',
                label: '02 – Therme & Spa',
                fields: [
                  { type: 'string', name: 'number', label: 'Number (e.g. "02")' },
                  { type: 'string', name: 'heading', label: 'Heading' },
                  { type: 'string', name: 'body', label: 'Description', ui: { component: 'textarea' } },
                ],
              },
              {
                type: 'object',
                name: 'nature',
                label: '03 – Allgäuer Natur',
                fields: [
                  { type: 'string', name: 'number', label: 'Number (e.g. "03")' },
                  { type: 'string', name: 'heading', label: 'Heading' },
                  { type: 'string', name: 'body', label: 'Description', ui: { component: 'textarea' } },
                ],
              },
            ],
          },
          {
            type: 'object',
            name: 'packages_section',
            label: 'Packages Section (Headings)',
            fields: [
              { type: 'string', name: 'caption', label: 'Category Label (e.g. "Pakete & Angebote")' },
              { type: 'string', name: 'heading', label: 'Section Heading' },
              { type: 'string', name: 'all_link_label', label: '"All Packages" Button Text' },
            ],
          },
          {
            type: 'object',
            name: 'rooms_section',
            label: 'Rooms Section (Headings)',
            fields: [
              { type: 'string', name: 'caption', label: 'Category Label' },
              { type: 'string', name: 'heading', label: 'Section Heading' },
              { type: 'string', name: 'body', label: 'Intro Text', ui: { component: 'textarea' } },
              { type: 'string', name: 'all_link_label', label: '"All Rooms" Button Text' },
              { type: 'image', name: 'featured_image', label: 'Featured Preview Image' },
            ],
          },
          {
            type: 'object',
            name: 'therme_cta',
            label: 'Thermal Spa Section',
            fields: [
              { type: 'image', name: 'background_image', label: 'Background Image' },
              { type: 'string', name: 'caption', label: 'Category Label' },
              { type: 'string', name: 'heading', label: 'Section Heading' },
              { type: 'string', name: 'body', label: 'Description', ui: { component: 'textarea' } },
              { type: 'string', name: 'stat_1_value', label: 'Stat 1 Value (e.g. "1.500 m²")' },
              { type: 'string', name: 'stat_1_label', label: 'Stat 1 Label' },
              { type: 'string', name: 'stat_2_value', label: 'Stat 2 Value' },
              { type: 'string', name: 'stat_2_label', label: 'Stat 2 Label' },
              { type: 'string', name: 'stat_3_value', label: 'Stat 3 Value' },
              { type: 'string', name: 'stat_3_label', label: 'Stat 3 Label' },
              { type: 'string', name: 'cta_primary_label', label: 'Primary Button Text' },
              { type: 'string', name: 'cta_secondary_label', label: 'Secondary Button Text' },
            ],
          },
          {
            type: 'object',
            name: 'voucher_strip',
            label: 'Gift Vouchers Section',
            fields: [
              { type: 'string', name: 'caption', label: 'Category Label' },
              { type: 'string', name: 'heading', label: 'Heading' },
              { type: 'string', name: 'subheading', label: 'Second Line (italic)' },
            ],
          },
        ],
      },
      {
        name: 'hotel',
        label: 'Hotel & Resort Page',
        path: 'src/content/pages',
        format: 'json',
        match: { include: 'hotel.json' },
        ui: { allowedActions: { create: false, delete: false }, router: () => '/hotel' },
        fields: [
          { type: 'string', name: 'seo_title', label: 'SEO Title (Browser Tab)' },
          { type: 'string', name: 'seo_description', label: 'SEO Description (Google)', ui: { component: 'textarea' } },
          { type: 'string', name: 'hero_caption', label: 'Hero Caption' },
          { type: 'string', name: 'hero_heading', label: 'Hero Heading' },
          { type: 'string', name: 'hero_intro', label: 'Hero Intro', ui: { component: 'textarea' } },
          { type: 'image', name: 'hero_image', label: 'Hero Image' },
          { type: 'string', name: 'hero_image_alt', label: 'Hero Image Alt Text' },
          { type: 'string', name: 'intro_heading', label: 'Intro Heading' },
          { type: 'string', name: 'intro_body', label: 'Intro Body', ui: { component: 'textarea' } },
          { type: 'image', name: 'intro_image', label: 'Intro Image' },
          { type: 'string', name: 'highlight_1_heading', label: 'Highlight 1 Heading' },
          { type: 'string', name: 'highlight_1_body', label: 'Highlight 1 Body', ui: { component: 'textarea' } },
          { type: 'string', name: 'highlight_2_heading', label: 'Highlight 2 Heading' },
          { type: 'string', name: 'highlight_2_body', label: 'Highlight 2 Body', ui: { component: 'textarea' } },
          { type: 'string', name: 'highlight_3_heading', label: 'Highlight 3 Heading' },
          { type: 'string', name: 'highlight_3_body', label: 'Highlight 3 Body', ui: { component: 'textarea' } },
        ],
      },
      {
        name: 'therme',
        label: 'Therme Page',
        path: 'src/content/pages',
        format: 'json',
        match: { include: 'therme.json' },
        ui: { allowedActions: { create: false, delete: false }, router: () => '/therme' },
        fields: [
          { type: 'string', name: 'seo_title', label: 'SEO Title (Browser Tab)' },
          { type: 'string', name: 'seo_description', label: 'SEO Description (Google)', ui: { component: 'textarea' } },
          { type: 'string', name: 'hero_caption', label: 'Hero Caption' },
          { type: 'string', name: 'hero_heading', label: 'Hero Heading' },
          { type: 'string', name: 'hero_intro', label: 'Hero Intro', ui: { component: 'textarea' } },
          { type: 'image', name: 'hero_image', label: 'Hero Image' },
          { type: 'string', name: 'hero_image_alt', label: 'Hero Image Alt Text' },
          { type: 'string', name: 'intro_heading', label: 'Intro Heading' },
          { type: 'string', name: 'intro_body', label: 'Intro Body', ui: { component: 'textarea' } },
          { type: 'image', name: 'intro_image', label: 'Intro Image' },
          { type: 'string', name: 'stat_1_value', label: 'Stat 1 Value (e.g. "1.500 m²")' },
          { type: 'string', name: 'stat_1_label', label: 'Stat 1 Label' },
          { type: 'string', name: 'stat_2_value', label: 'Stat 2 Value' },
          { type: 'string', name: 'stat_2_label', label: 'Stat 2 Label' },
          { type: 'string', name: 'stat_3_value', label: 'Stat 3 Value' },
          { type: 'string', name: 'stat_3_label', label: 'Stat 3 Label' },
        ],
      },
      {
        name: 'gesundheit',
        label: 'Gesundheit Page',
        path: 'src/content/pages',
        format: 'json',
        match: { include: 'gesundheit.json' },
        ui: { allowedActions: { create: false, delete: false }, router: () => '/gesundheit' },
        fields: [
          { type: 'string', name: 'seo_title', label: 'SEO Title (Browser Tab)' },
          { type: 'string', name: 'seo_description', label: 'SEO Description (Google)', ui: { component: 'textarea' } },
          { type: 'string', name: 'hero_caption', label: 'Hero Caption' },
          { type: 'string', name: 'hero_heading', label: 'Hero Heading' },
          { type: 'string', name: 'hero_intro', label: 'Hero Intro', ui: { component: 'textarea' } },
          { type: 'image', name: 'hero_image', label: 'Hero Image' },
          { type: 'string', name: 'hero_image_alt', label: 'Hero Image Alt Text' },
          { type: 'string', name: 'intro_heading', label: 'Intro Heading' },
          { type: 'string', name: 'intro_body', label: 'Intro Body', ui: { component: 'textarea' } },
          { type: 'image', name: 'intro_image', label: 'Intro Image' },
        ],
      },
      {
        name: 'kulinarik',
        label: 'Kulinarik Page',
        path: 'src/content/pages',
        format: 'json',
        match: { include: 'kulinarik.json' },
        ui: { allowedActions: { create: false, delete: false }, router: () => '/kulinarik' },
        fields: [
          { type: 'string', name: 'seo_title', label: 'SEO Title (Browser Tab)' },
          { type: 'string', name: 'seo_description', label: 'SEO Description (Google)', ui: { component: 'textarea' } },
          { type: 'string', name: 'hero_caption', label: 'Hero Caption' },
          { type: 'string', name: 'hero_heading', label: 'Hero Heading' },
          { type: 'string', name: 'hero_intro', label: 'Hero Intro', ui: { component: 'textarea' } },
          { type: 'image', name: 'hero_image', label: 'Hero Image' },
          { type: 'string', name: 'hero_image_alt', label: 'Hero Image Alt Text' },
          { type: 'string', name: 'intro_heading', label: 'Intro Heading' },
          { type: 'string', name: 'intro_body', label: 'Intro Body', ui: { component: 'textarea' } },
          { type: 'image', name: 'intro_image', label: 'Intro Image' },
          {
            type: 'object',
            name: 'venues',
            label: 'Venues (Restaurant, FEELbar, Café)',
            list: true,
            fields: [
              { type: 'string', name: 'name', label: 'Name' },
              { type: 'string', name: 'tagline', label: 'Tagline' },
              { type: 'image', name: 'image', label: 'Image' },
              { type: 'string', name: 'body', label: 'Description', ui: { component: 'textarea' } },
              { type: 'string', name: 'highlight', label: 'Highlight Note (optional, e.g. "Ladies Night")' },
              { type: 'string', name: 'note', label: 'Status Note (optional, e.g. "Momentan geschlossen")' },
              { type: 'string', name: 'hours', label: 'Opening Hours (one per line)', list: true },
            ],
          },
          { type: 'string', name: 'buffet_heading', label: 'Buffet Section Heading' },
          {
            type: 'object',
            name: 'buffet_items',
            label: 'Buffet Price List',
            list: true,
            fields: [
              { type: 'string', name: 'label', label: 'Item Label' },
              { type: 'string', name: 'price', label: 'Price (e.g. "22,00 €")' },
            ],
          },
          { type: 'string', name: 'buffet_note', label: 'Buffet Note (discounts, etc.)', ui: { component: 'textarea' } },
        ],
      },
      {
        name: 'allgaeu',
        label: 'Allgäu erleben Page',
        path: 'src/content/pages',
        format: 'json',
        match: { include: 'allgaeu.json' },
        ui: { allowedActions: { create: false, delete: false }, router: () => '/allgaeu' },
        fields: [
          { type: 'string', name: 'seo_title', label: 'SEO Title (Browser Tab)' },
          { type: 'string', name: 'seo_description', label: 'SEO Description (Google)', ui: { component: 'textarea' } },
          { type: 'string', name: 'hero_caption', label: 'Hero Caption' },
          { type: 'string', name: 'hero_heading', label: 'Hero Heading' },
          { type: 'string', name: 'hero_intro', label: 'Hero Intro', ui: { component: 'textarea' } },
          { type: 'image', name: 'hero_image', label: 'Hero Image' },
          { type: 'string', name: 'hero_image_alt', label: 'Hero Image Alt Text' },
          { type: 'string', name: 'intro_heading', label: 'Intro Heading' },
          { type: 'string', name: 'intro_body', label: 'Intro Body', ui: { component: 'textarea' } },
          { type: 'image', name: 'intro_image', label: 'Intro Image' },
          {
            type: 'object',
            name: 'activities',
            label: 'Activity Cards',
            list: true,
            fields: [
              { type: 'string', name: 'title', label: 'Title' },
              { type: 'image', name: 'image', label: 'Image' },
              { type: 'string', name: 'body', label: 'Description', ui: { component: 'textarea' } },
            ],
          },
          {
            type: 'object',
            name: 'features',
            label: 'Feature Sections (Wurzacher Ried, Podkäschtle)',
            list: true,
            fields: [
              { type: 'string', name: 'heading', label: 'Heading' },
              { type: 'image', name: 'image', label: 'Image' },
              { type: 'string', name: 'image_alt', label: 'Image Alt Text' },
              { type: 'string', name: 'paragraphs', label: 'Paragraphs (one per line)', list: true, ui: { component: 'textarea' } },
              {
                type: 'object',
                name: 'links',
                label: 'External Links',
                list: true,
                fields: [
                  { type: 'string', name: 'label', label: 'Link Text' },
                  { type: 'string', name: 'href', label: 'URL' },
                ],
              },
            ],
          },
        ],
      },
      {
        name: 'gutscheine',
        label: 'Gutscheine Page',
        path: 'src/content/pages',
        format: 'json',
        match: { include: 'gutscheine.json' },
        ui: { allowedActions: { create: false, delete: false }, router: () => '/gutscheine' },
        fields: [
          { type: 'string', name: 'seo_title', label: 'SEO Title (Browser Tab)' },
          { type: 'string', name: 'seo_description', label: 'SEO Description (Google)', ui: { component: 'textarea' } },
          { type: 'string', name: 'hero_caption', label: 'Hero Caption' },
          { type: 'string', name: 'hero_heading', label: 'Hero Heading' },
          { type: 'string', name: 'hero_intro', label: 'Hero Intro', ui: { component: 'textarea' } },
          { type: 'image', name: 'hero_image', label: 'Hero Image' },
          { type: 'string', name: 'hero_image_alt', label: 'Hero Image Alt Text' },
          { type: 'string', name: 'intro_heading', label: 'Intro Heading' },
          { type: 'string', name: 'intro_body', label: 'Intro Body', ui: { component: 'textarea' } },
          { type: 'image', name: 'intro_image', label: 'Intro Image' },
          { type: 'string', name: 'intro_quote', label: 'Intro Quote' },
          { type: 'string', name: 'steps_heading', label: '"How It Works" Heading' },
          { type: 'string', name: 'steps', label: 'Steps (one per line)', list: true, ui: { component: 'textarea' } },
          { type: 'string', name: 'categories_heading', label: 'Categories Heading' },
          { type: 'string', name: 'categories_intro', label: 'Categories Intro', ui: { component: 'textarea' } },
          {
            type: 'object',
            name: 'categories',
            label: 'Voucher Categories',
            list: true,
            fields: [
              { type: 'string', name: 'name', label: 'Name' },
              { type: 'image', name: 'image', label: 'Image' },
            ],
          },
          { type: 'string', name: 'partner_heading', label: 'Partner Section Heading' },
          { type: 'string', name: 'partner_body', label: 'Partner Section Body', ui: { component: 'textarea' } },
          { type: 'string', name: 'cta_buy_label', label: 'Buy Button Text' },
          { type: 'string', name: 'cta_buy_href', label: 'Buy Button Link' },
        ],
      },
      {
        name: 'rooms',
        label: 'Rooms & Suites',
        path: 'src/content/rooms',
        format: 'md',
        ui: {
          router: ({ document }) => `/zimmer/${document._sys.filename}`,
        },
        fields: [
          { type: 'string', name: 'name', label: 'Room Name', isTitle: true, required: true },
          { type: 'string', name: 'variants', label: 'Room Categories (e.g. "Comfort · Classic")' },
          { type: 'string', name: 'tagline', label: 'Short Tagline' },
          { type: 'string', name: 'size', label: 'Room Size (e.g. "ab 28 m²")' },
          { type: 'string', name: 'capacity', label: 'Occupancy' },
          { type: 'boolean', name: 'highlight', label: 'Show "Popular" Badge?' },
          { type: 'number', name: 'sort_order', label: 'Display Order in Listing (1 = first)' },
          { type: 'string', name: 'seo_title', label: 'SEO Title' },
          { type: 'string', name: 'seo_description', label: 'SEO Description', ui: { component: 'textarea' } },
          { type: 'image', name: 'hero_image', label: 'Hero Image (detail page)' },
          { type: 'image', name: 'preview_image', label: 'Preview Image (listing card)' },
          {
            type: 'object',
            name: 'gallery',
            label: 'Photo Gallery',
            list: true,
            fields: [
              { type: 'image', name: 'image', label: 'Photo' },
              { type: 'string', name: 'caption', label: 'Caption' },
            ],
          },
          { type: 'string', name: 'intro_heading', label: 'Description Section Heading' },
          { type: 'string', name: 'intro_subheading', label: 'Description Subheading' },
          {
            type: 'object',
            name: 'specs',
            label: 'Room Data (sidebar)',
            list: true,
            fields: [
              { type: 'string', name: 'label', label: 'Label' },
              { type: 'string', name: 'value', label: 'Value' },
            ],
          },
          {
            type: 'object',
            name: 'feature_groups',
            label: 'Amenity Groups',
            list: true,
            fields: [
              { type: 'string', name: 'heading', label: 'Group Heading' },
              { type: 'string', name: 'items', label: 'Features (one per line)', list: true },
            ],
          },
          { type: 'rich-text', name: 'body', label: 'Description', isBody: true },
        ],
      },
      {
        name: 'packages',
        label: 'Packages & Offers',
        path: 'src/content/packages',
        format: 'md',
        ui: {
          router: ({ document }) => `/angebote/${document._sys.filename}`,
        },
        fields: [
          { type: 'string', name: 'title', label: 'Package Name', isTitle: true, required: true },
          {
            type: 'string',
            name: 'tag',
            label: 'Category',
            options: [
              'Heilung & Regeneration',
              'Entschlackung & Entgiftung',
              'Entschleunigung & Wellness',
              'Saisonal & Specials',
            ],
          },
          { type: 'string', name: 'subtitle', label: 'Subtitle / Tagline' },
          { type: 'string', name: 'nights', label: 'Duration (e.g. "2 Nächte")' },
          { type: 'string', name: 'teaser', label: 'Short Description (homepage card)', ui: { component: 'textarea' } },
          { type: 'image', name: 'image', label: 'Preview Image' },
          { type: 'string', name: 'image_alt', label: 'Image Alt Text' },
          { type: 'number', name: 'price_from', label: 'Starting Price in EUR' },
          { type: 'string', name: 'price_label', label: 'Price Suffix' },
          { type: 'string', name: 'booking_link', label: 'Booking Link (single option)' },
          {
            type: 'object',
            name: 'booking_options',
            label: 'Booking Options (multiple durations)',
            list: true,
            fields: [
              { type: 'string', name: 'label', label: 'Duration Label' },
              { type: 'string', name: 'href', label: 'Booking URL' },
            ],
          },
          { type: 'number', name: 'nav_order', label: 'Nav Order in Mega Menu' },
          { type: 'boolean', name: 'show_in_nav', label: 'Show in Angebote Mega Menu?' },
          { type: 'string', name: 'includes', label: "What's Included", list: true },
          { type: 'string', name: 'inclusion_note', label: 'Note Below Inclusions List', ui: { component: 'textarea' } },
          { type: 'string', name: 'recommendations', label: 'Our Recommendation (bullet list)', list: true },
          { type: 'string', name: 'availability', label: 'Dates / Availability', ui: { component: 'textarea' } },
          { type: 'string', name: 'availability_note', label: 'Availability Note', ui: { component: 'textarea' } },
          {
            type: 'object',
            name: 'pricing_tiers',
            label: 'Pricing Tiers',
            list: true,
            fields: [
              { type: 'string', name: 'duration', label: 'Duration' },
              { type: 'number', name: 'price_from', label: 'From Price in EUR' },
              { type: 'string', name: 'price_note', label: 'Price Note' },
              { type: 'string', name: 'href', label: 'Booking URL' },
            ],
          },
          {
            type: 'object',
            name: 'highlights',
            label: 'Feature Highlights (cards)',
            list: true,
            fields: [
              { type: 'string', name: 'title', label: 'Title' },
              { type: 'string', name: 'text', label: 'Text', ui: { component: 'textarea' } },
            ],
          },
          { type: 'string', name: 'program_intro', label: 'Program Intro', ui: { component: 'textarea' } },
          {
            type: 'object',
            name: 'points_catalog',
            label: 'Points Catalog (Punktekatalog)',
            list: true,
            fields: [
              { type: 'string', name: 'points', label: 'Points Label (e.g. "11 Punkte")' },
              { type: 'string', name: 'items', label: 'Treatments (separate with |)', ui: { component: 'textarea' } },
            ],
          },
          { type: 'string', name: 'program_columns', label: 'Program Table Columns', list: true },
          {
            type: 'object',
            name: 'program_rows',
            label: 'Program Table Rows',
            list: true,
            fields: [
              { type: 'string', name: 'treatment', label: 'Treatment' },
              { type: 'string', name: 'effect', label: 'Effect', ui: { component: 'textarea' } },
              { type: 'string', name: 'values', label: 'Values per Column (in order)', list: true },
            ],
          },
          {
            type: 'object',
            name: 'gallery',
            label: 'Image Gallery',
            list: true,
            fields: [
              { type: 'image', name: 'image', label: 'Photo' },
              { type: 'string', name: 'alt', label: 'Alt Text' },
            ],
          },
          { type: 'string', name: 'closing_heading', label: 'Closing Section Heading (e.g. "Warum ins Moor?")' },
          { type: 'string', name: 'closing_body', label: 'Closing Section Text', ui: { component: 'textarea' } },
          { type: 'rich-text', name: 'body', label: 'Article Body', isBody: true },
        ],
      },
      {
        name: 'blog',
        label: 'News & Blog Posts',
        path: 'src/content/blog',
        format: 'md',
        fields: [
          { type: 'string', name: 'title', label: 'Headline', isTitle: true, required: true },
          { type: 'string', name: 'seo_title', label: 'SEO Title' },
          { type: 'string', name: 'seo_description', label: 'SEO Description', ui: { component: 'textarea' } },
          { type: 'string', name: 'date', label: 'Date (YYYY-MM-DD)' },
          { type: 'string', name: 'author', label: 'Author' },
          { type: 'string', name: 'category', label: 'Category' },
          { type: 'string', name: 'teaser', label: 'Teaser', ui: { component: 'textarea' } },
          { type: 'image', name: 'image', label: 'Featured Image' },
          { type: 'string', name: 'image_alt', label: 'Featured Image Alt Text' },
          { type: 'rich-text', name: 'body', label: 'Article Content', isBody: true },
        ],
        ui: {
          router: ({ document }) => `/blog/${document._sys.filename}`,
        },
      },
      {
        name: 'settings',
        label: 'Global Settings',
        path: 'src/content/settings',
        format: 'json',
        match: { include: 'site.json' },
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: 'string', name: 'hotel_name', label: 'Hotel Name' },
          { type: 'string', name: 'tagline', label: 'Hotel Tagline' },
          { type: 'string', name: 'address_street', label: 'Street Address' },
          { type: 'string', name: 'address_zip_city', label: 'Postcode & City' },
          { type: 'string', name: 'address_region', label: 'State / Region' },
          { type: 'string', name: 'address_country', label: 'Country' },
          { type: 'string', name: 'phone_display', label: 'Phone Number (display, e.g. "+49 7564 30-1000")' },
          { type: 'string', name: 'phone_link', label: 'Phone Number (tel link, no spaces)' },
          { type: 'string', name: 'email', label: 'Email Address' },
          { type: 'string', name: 'social_instagram', label: 'Instagram Link' },
          { type: 'string', name: 'social_facebook', label: 'Facebook Link' },
          { type: 'image', name: 'default_og_image', label: 'Default Social Preview Image' },
          { type: 'string', name: 'copyright_name', label: 'Copyright Text' },
          {
            type: 'object',
            name: 'header_nav_links',
            label: 'Header Mega Menu — Extra Links',
            list: true,
            fields: [
              { type: 'string', name: 'mega_menu_id', label: 'Section (hotel | therme | gesundheit | angebote | allgaeu)' },
              { type: 'string', name: 'column_heading', label: 'Column Heading (must match exactly)' },
              { type: 'string', name: 'label', label: 'Link Text' },
              { type: 'string', name: 'href', label: 'URL Path' },
              { type: 'number', name: 'sort_order', label: 'Order Among Manual Links' },
            ],
          },
          {
            type: 'object',
            name: 'footer_columns',
            label: 'Footer Navigation',
            list: true,
            fields: [
              { type: 'string', name: 'heading', label: 'Column Heading' },
              {
                type: 'object',
                name: 'links',
                label: 'Links',
                list: true,
                fields: [
                  { type: 'string', name: 'label', label: 'Link Text' },
                  { type: 'string', name: 'href', label: 'Link URL' },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
});
